/**
 * Curated search lexicon for the Butwal, Nepal catalogue.
 *
 * This is a *domain lexicon*, not data: it contains no restaurants or dishes and
 * is never rendered to users. It exists so fuzzy/typo-tolerant matching has real
 * words to compare against ("mommo" -> "momo", "piza" -> "pizza") even before a
 * database vocabulary is built, and so typo tolerance works from any module
 * without creating cross-module dependencies.
 *
 * Terms mirror the cuisines, categories and dish families actually present in the
 * KhanaGo dataset (momo, chowmein, sekuwa, thakali, dhido, pizza, biryani, cafe...).
 */
export const FOOD_VOCABULARY: string[] = [
  // Nepali / Newari / Thakali staples
  'momo',
  'momos',
  'chicken momo',
  'veg momo',
  'buff momo',
  'kothey momo',
  'c momo',
  'jhol momo',
  'steam momo',
  'fried momo',
  'thukpa',
  'chowmein',
  'chow mein',
  'thakali',
  'thali',
  'dal bhat',
  'khana set',
  'dhido',
  'dhindo',
  'fapar',
  'kodo',
  'gundruk',
  'sekuwa',
  'sekwa',
  'sukuti',
  'chiura',
  'baji',
  'samay baji',
  'chhoyela',
  'sandheko',
  'aloo',
  'tama',
  'bodi',
  'gundruk sandheko',
  'sisnu',
  'achar',
  'papad',
  'newari',
  'khaja',
  'nasta',
  'sel roti',
  'chatamari',
  'yomari',
  'kwati',
  // Indian / Mughlai / Tandoori
  'biryani',
  'biriyani',
  'butter chicken',
  'paneer',
  'naan',
  'roti',
  'paratha',
  'tandoori',
  'tikka',
  'kebab',
  'seekh',
  'curry',
  'masala',
  'dosa',
  'dum aloo',
  'lassi',
  'gulab jamun',
  'jalebi',
  'kulfi',
  'samosa',
  'pakora',
  'chaat',
  'pani puri',
  // Chinese / Indo-Chinese
  'chinese',
  'schezwan',
  'manchurian',
  'fried rice',
  'spring roll',
  'chilli',
  'hakka noodles',
  'chowmin',
  'momos chowmein',
  'soup',
  'hot and sour',
  // Continental / Italian / Cafe
  'pizza',
  'pasta',
  'spaghetti',
  'lasagna',
  'macaroni',
  'risotto',
  'calzone',
  'burger',
  'cheeseburger',
  'sandwich',
  'panini',
  'wrap',
  'roll',
  'fries',
  'french fries',
  'wings',
  'nuggets',
  'popcorn chicken',
  'sizzler',
  'steak',
  'salad',
  'caesar salad',
  'nachos',
  'tacos',
  'burrito',
  'quesadilla',
  'coffee',
  'espresso',
  'cappuccino',
  'latte',
  'americano',
  'cold coffee',
  'mocha',
  'macchiato',
  'frappe',
  'shake',
  'milkshake',
  'smoothie',
  'chiya',
  'tea',
  'milk tea',
  'masala tea',
  'green tea',
  'lemon tea',
  'iced tea',
  'mocktail',
  'mojito',
  'lemonade',
  'soda',
  'juice',
  'lassi',
  'buttermilk',
  // Bakery / desserts
  'bakery',
  'cake',
  'cheesecake',
  'brownie',
  'pastry',
  'croissant',
  'donut',
  'waffle',
  'pancake',
  'ice cream',
  'dessert',
  'sweet',
  'muffin',
  'cinnamon roll',
  // Grill / protein keywords used in query examples
  'chicken',
  'mutton',
  'buff',
  'pork',
  'fish',
  'seafood',
  'prawn',
  'paneer',
  'veg',
  'vegetarian',
  'vegan',
  'egg',
  'cheese',
  'mushroom',
  'corn',
  // Cuisines / venue types users search for
  'nepali',
  'indian',
  'chinese',
  'tibetan',
  'italian',
  'continental',
  'mexican',
  'mughlai',
  'hyderabadi',
  'american',
  'asian',
  'fusion',
  'cafe',
  'bakery',
  'fast food',
  'street food',
  'breakfast',
  'bar',
  'lounge',
  'restaurant',
  'restro',
  'multi cuisine',
  'desserts',
  'drinks',
  'snacks',
  'kebabs',
  'sizzlers',
  'grill',
];

/** Deduplicated lexicon used for fuzzy expansion. */
export const FOOD_VOCABULARY_UNIQUE: string[] = [...new Set(FOOD_VOCABULARY)];
